export const ADD_REMINDER = 'ADD_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';

export const SHOW_NEW_REMINDER_FORM = 'SHOW_NEW_REMINDER_FORM';
export const CLOSE_REMINDER_FORM = 'CLOSE_REMINDER_FORM';
